---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    restart: no
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./strategies_${TIME_FRAME-5m}:/freqtrade/user_data/strategies"
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      backtesting
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
      --strategy-list SampleStrategy
      --stake-amount ${STAKE_AMOUNT:-unlimited}
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --timerange ${TIMERANGE}
      --enable-protections
      --i ${TIME_FRAME:-5m}