---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    restart: "no"
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      backtesting
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
      --strategy-list ${STRATEGYLIST}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --timerange ${TIMERANGE}
      --enable-protections
      --timeframe ${TIME_FRAME:-5m}
      --export trades
      --export-filename user_data/backtest_results/${EXCHANGE:-binance}-${TIME_FRAME:-5m}-${TIMERANGE}.json