# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Pre-Commit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.4.0
  Backtests:
    runs-on: ubuntu-latest
    # needs:
    #   - Pre-Commit
    strategy:
      fail-fast: false
      matrix:
      # timeranges from MoniGomani ( Down, Up, Side, Final )
        timerange:
          - 20210509-20210524 
          - 20210127-20210221
          - 20210518-20210610
          - 20210425-20210610
        exchange:
          - binance
          - kucoin
        timeframe:
          - 5m
          - 15m
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              -'user_data/strategies/**'
              -'*.env'
              -'.github/workflows/**'
      - name: Strategy Lists to be tested in ${{matrix.timeframe}}
        id: strategylist
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true
          path:
            strategylist_${{matrix.timeframe}}.env
      - name: run backtests
        if: steps.changes.outputs.src == 'true'
        env:
          TIME_FRAME: ${{ matrix.timeframe}}
          TIMERANGE: ${{ matrix.timerange }}
          EXCHANGE: ${{ matrix.exchange }}
          STRATEGYLIST: ${{ steps.strategylist.outputs.STRATEGYLIST}}
        run: docker-compose up
      - name: upload logs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.timeframe}}-backtest-data
          path: user_data/backtest_results/*.json
          retention-days: 7
  Backtest-CI-Stats:
    runs-on: ubuntu-latest
    needs: 
      - Backtests
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Download all artifact
        uses: actions/download-artifact@v2
# add some things to update a results file.. ?