# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'results/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Pre-Commit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.4.0
  Backtests:
    runs-on: ubuntu-latest
    # needs:
    #   - Pre-Commit
    strategy:
      fail-fast: false
      matrix:
      # timeranges from MoniGomani ( Down, Up, Side, Final )
        timerange:
          - 20210509-20210524 
          - 20210127-20210221
          - 20210518-20210610
          - 20210425-20210610
        exchange:
          - binance
          # - kucoin
        timeframe:
          - 1m
          - 5m
          # Currently no strats here....
          # - 15m
          # - 1h
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Remove File
        run: rm -rf results/*.md
      - run: ls -R
      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '17.4.0'

      - name: install node modules
        run: npm install
        working-directory: tools

      - name: Strategy Lists to be tested in ${{matrix.timeframe}}
        id: strategylist
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true
          path:
            strategylist_${{matrix.timeframe}}.env

      - name: run backtests
        # if: steps.changes.outputs.src == 'true'
        env:
          TIME_FRAME: ${{ matrix.timeframe}}
          TIMERANGE: ${{ matrix.timerange }}
          EXCHANGE: ${{ matrix.exchange }}
          STRATEGYLIST: ${{ steps.strategylist.outputs.STRATEGYLIST}}
        run: docker-compose up
      - run: node index.js -o ../results -b ../user_data/backtest_results -e ${{ matrix.exchange }} -t ${{ matrix.timeframe}} -r ${{ matrix.timerange }}
        working-directory: tools
      
      - run: ls -R

      # - uses: EndBug/add-and-commit@v8
      #   with:
      #     add: 'results'
      #     pull: '--rebase --autostash'
      - name: upload md as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results
          retention-days: 1
      - name: upload logs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: user_data/backtest_results
          retention-days: 1

  Backtest-CI-Stats:
    runs-on: ubuntu-latest
    needs: 
      - Backtests
    steps:

      - uses: actions/checkout@v2.4.0
      - run: rm -rf results
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          name: results
          path: results
      - uses: EndBug/add-and-commit@v8
        with:
          add: 'results'
          push: true
          #pull: '--rebase --autostash'
      - run: ls -R
# add some things to update a results file.. ?
