# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
  Backtests:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    strategy:
      fail-fast: false
      matrix:
      # timeranges from MoniGomani ( Down, Up, Side, Final )
        timerange:
          - 20210509-20210524 
          - 20210127-20210221
          - 20210518-20210610
          - 20210425-20210610
        exchange:
          - binance
          - kucoin
        timeframe:
          - 5m
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Strategy Lists to be tested in ${{matrix.timeframe}}
        id: strategylist
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true
          path:
            strategylist_${{matrix.timeframe}}.env
      - name: run backtests
        env:
          TIME_FRAME: ${{ matrix.timeframe}}
          TIMERANGE: ${{ matrix.timerange }}
          EXCHANGE: ${{ matrix.exchange }}
          STRATEGYLIST: ${{ steps.strategylist.output.STRATEGYLIST}}
        run: docker-compose up
